config/routes.rb
Rails.application.routes.draw do
  root "appointments#index"

  devise_for :recruiters
  devise_for :users

  resources :appointments do
    devise_for :users
  end

  namespace :recruiter do
    resources :appointments
  end
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  extend SimpleCalendar
  has_calendar :attribute => :scheduled_time
  belongs_to :recruiter
  belongs_to :user
  validates_presence_of :scheduled_time
  validates_presence_of :location

  def availability
    if user == nil
      "Available"
    else
      user.formatted_name
    end
  end

  def info
    user.stats
  end

  def message
    "Book an appointment at #{scheduled_time.strftime("%l:%M %P")} in #{location}?"
  end

  def user_name
    user.first_name
  end

  def user_email
    user.email
  end

  def candidateurl
    "https://cls2.bullhornstaffing.com/BullhornSTAFFING/OpenWindow.cfm?Entity=Candidate&ID=4800477"
  end
end

app/models/recruiter.rb
class Recruiter < ActiveRecord::Base
  has_many :appointments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :appointment
  validates :email, presence: true, uniqueness: true, email: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def formatted_name
    "#{first_name} #{last_name}"
  end

  def stats
    "#{degree} | #{major} | #{year}"
  end

  def bullhorn_address
    "https://cls2.bullhornstaffing.com/BullhornSTAFFING/OpenWindow.cfm?Entity=Candidate&ID=#{bullhorn_id}"
  end

  def password_required?
    false
  end
end

app/controllers/User/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/User/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController

  def book_appointment
    repond_to do |format|
      format.js
    end
  end
end

app/controllers/User/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/User/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email,
                                                            :password,
                                                            :password_confirmation,
                                                            :first_name,
                                                            :last_name,
                                                            :major,
                                                            :year,
                                                            :degree) }
  end

  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @appointments = Appointment.all
  end

  def new
    @appointment = Appointment.new
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
    appointment = Appointment.find(params[:id])
    @appointment = appointment
    @appointment.update(appointment_params)
    @appointment.save
    user = current_user
    UserMailer.booking_email(user, appointment).deliver
    respond_with(appointment)
    redirect_to appointments_path
  end

private
  def appointment_params
    params.require(:appointment).permit(:user_id, :booked)
  end
end

app/controllers/recruiter/appointments_controller.rb
class Recruiter::AppointmentsController < ApplicationController

  def index
    @appointments = Appointment.all
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
    @appointment = Appointment.(params[:id])

    if @appointment.update(appointment_params)
      redirect_to appointments_path
    else
      render :new
    end
  end

  def appointment_params
    params.require(:appointment).permit(:scheduled_time, :location, :recruiter_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment_helper.rb
module AppointmentHelper

  def link_to_user(user)
      link_to user.formatted_name,
              user_path(user)
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div id="flash">
    <% flash.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_topbar.html.erb
<nav class="topbar">
  <%= link_to recruiter_appointments_path do %>
    <%= image_tag('microsoft.png') %>
  <% end %>
</nav>

---
<nav class="topbar">
  <%= link_to recruiter_appointments_path do %>
    <%= image_tag('microsoft.png') %>
  <% end %>
</nav>
<div class="candidatebar">
  <p><%=link_to 'Sign In', new_user_session_path %> or click on an appointment to schedule.</p>
</div>

app/views/appointments/_book.html.erb
<%= simple_form_for [appointment], method: :patch do |f| %>
  <%= f.hidden_field :booked, booked: appointment.booked %>
      <% appointment.booked = true %>
      <% appointment.user = current_user %>
      <% appointment.save %>
      <h1>Thank You</h1>
      <p><%= appointment.scheduled_time.strftime("%A, %B %d")%>th at  <%appointment.scheduled_time.strftime("%l:%M% P")%>
        has been booked for you!</p>
<% end %>
<%= link_to "Return to Schedule", appointments_path %>

app/views/appointments/_signup.html.erb
<h2>The Age of You Has Begun</h2>
<h3>Achieve Your Potential. Start Here.</h3>


<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name, required: true %>
    <%= f.input :last_name, required: true %>
    <%= f.input :degree do %>
      <%= f.select :degree, ["BS", "BE", "MBA"] %>
    <% end %>
    <%= f.input :major, required: true %>
    <%= f.input :year, required: true %>
    <%= f.input :email, required: true, autofocus: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Book It!" %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<div class="logo">
<%= image_tag('logo3.png') %>
</div>
<div class="message">
<%= simple_form_for @appointment, method: :patch do |f| %>
  <%= f.hidden_field :booked, booked: @appointment.booked %>
      <% @appointment.booked = true %>
      <% @appointment.user = current_user %>
      <% @appointment.save %>
      <h1>It's yours.</h1>
      <p>We've reserved <%= @appointment.scheduled_time.strftime("%B %d")%>th at  <%=@appointment.scheduled_time.strftime("%l:%M %P")%>
        <br>just for you.</p>
<% end %>
<%= link_to "Return to Schedule", destroy_user_session_path, method: :delete %>
</div>

app/views/appointments/index.html.erb
<nav class="topbar">
  <%= link_to root_path do %>
    <%= image_tag('logo3.png') %>
  <% end %>
  <hr>
</nav>
<div class="candidatebar">
  <a><%= link_to 'Log Out', destroy_user_session_path, :method => :delete %>
    <%= link_to('Log In', new_user_session_path) %></a>
</div>
<div class="candidate">
  <div class="candidate-calendar">
    <%= calendar number_of_days: 3, events: @appointments do |date, appointments| %>
    <div class="candidate_date">
      <%= date.strftime("%B %d, %Y") %>
    </div>
      <% appointments.each do |appointment| %>
        <% if appointment.booked? %>
          <div class="booked_appointment">
            <p><%= appointment.scheduled_time.strftime("%l:%M %P") %>
              Unavailable</p>
          </div>
        <% else %>
          <div class="available_appointment">
            <p><%= appointment.scheduled_time.strftime("%l:%M %P") %></p>
            <% if !current_user %>
              <%=  link_to 'Available', new_user_appointment_registration_path(appointment) %>
            <% else %>
              <%= link_to 'Available', edit_appointment_path(appointment) %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/appointments/new.html.erb
<h1>Create an Appointment</h1>
<%= simple_form_for @appointment do |f| %>
  <%= f.input :scheduled_time, label: 'Scheduled start time' %>
  <%= f.input :location, label: 'Location' %>
  <%= f.button :submit %>
<% end %>
<%= link_to 'Go Back', recruiter_appointments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <div class="content">
    <main>
      <%= yield %>
    </main>
  </div>
  <%= render "javascript" %>
</body>
</html>

app/views/recruiter/appointments/edit.html.erb
<h1>Change an Appointment</h1>
<%= simple_form_for @appointment do |f| %>
  <%= f.input :scheduled_time, label: 'Scheduled start time' %>
  <%= f.input :location, label: 'Location' %>
  <%= f.button :submit %>
<% end %>
<%= link_to 'Go Back', recruiter_appointments_path %>

app/views/recruiter/appointments/index.html.erb
<div class="recruiter_calendar">
<%=calendar number_of_days: 5,  events: @appointments do |date, appointments| %>
  <div class="date">
    <%= date.strftime("%B %d, %Y") %>
  </div>
  <hr>
  <% appointments.each do |appointment| %>
    <% if appointment.user %>
      <a href= "https://cls2.bullhornstaffing.com/BullhornSTAFFING/OpenWindow.cfm?Entity=Candidate&ID=4800550"><div class="recruiter_booked_appointment">
        <%= appointment.scheduled_time.strftime("%l:%M %P") %>
        <br>
        <strong><%= appointment.availability %></strong>
        <br>
        <%= appointment.info %>
      </div></a>
    <% else %>
      <div class="recruiter_available_appointment">
        <%= appointment.scheduled_time.strftime("%l:%M %P") %>
        <br>
        <p>No One Scheduled</p>
      </div>
    <% end %>
  <% end %>
<% end %>
</div>

app/views/users/new.html.erb
<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email, required: true, autofocus: true, prompt: "harry@uw.edu" %>
    <%= f.input :first_name, required: true, prompt: "Harry" %>
    <%= f.input :last_name, required: true, prompt: "Husky" %>
    <%= f.input :degree do %>
      <%= f.select :degree, [BS, BE, MBA] %>
    <% end %>
    <%= f.input :major, required: true, prompt: "Computer Science" %>
    <%= f.input :year, required: true, prompt: "2015" %>
    <%= f.input :password, required: true %>
    <%= f.input :password_confirmation, required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Sign up" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>